# -*- coding: utf-8 -*-
"""Crawwling_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nzl6xnrPJ4_GqBnYRNHRQMNIyHIBrqDo
"""

import requests
from bs4 import BeautifulSoup
import time
import re
import json
import os

# ==========================================
# CẤU HÌNH BAN ĐẦU
# ==========================================
# 1. Dùng Session để lưu trữ Cookie (Rất quan trọng để không bị văng)
SESSION = requests.Session()

# 2. Khai báo Header giả lập trình duyệt và AJAX
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'Content-Type': 'application/x-www-form-urlencoded',
    'X-Requested-With': 'XMLHttpRequest'
}

DANH_MUC_HOA = {
    "Tulip": 326,
    "Thúy châu": 323,
    "Scabiosa": 322,
    "Sen đá": 306,
    "Only rose": 296,
    "Hoa hồng": 261,
    "Mai mỹ": 277,
    "Thiên điểu": 276,
    "Hoa hạnh phúc": 275,
    "Hồng môn": 274,
    "Tú cầu": 273,
    "Mõm sói": 272,
    "Thạch thảo": 271,
    "Hướng dương": 268,
    "Hoa sen": 269,
    "Đồng tiền": 267,
    "Hoa lan": 266,
    "Cẩm chướng": 265,
    "Cát tường": 264,
    "Hoa Ly": 263,
    "Hoa baby": 270,
    "Hoa cúc": 262
}

FILE_KET_QUA = "database_hoa.json"
URL_GOC = "https://hoayeuthuong.com/hoa-tuoi/hoa-hong.aspx" # Dùng trang nào làm gốc cũng được

print("🚀 KHỞI ĐỘNG HỆ THỐNG THU THẬP DỮ LIỆU...\n")

# ==========================================
# TRẠM 1: LẤY THẺ THÔNG HÀNH (VIEWSTATE)
# ==========================================
print("⏳ TRẠM 1: Đang lấy mã bảo mật ViewState...")
res_get = SESSION.get(URL_GOC, headers=HEADERS)
soup_get = BeautifulSoup(res_get.text, 'html.parser')

try:
    viewstate = soup_get.find("input", {"id": "__VIEWSTATE"})["value"]
    viewstategenerator = soup_get.find("input", {"id": "__VIEWSTATEGENERATOR"})["value"]
    print("   -> ✅ Lấy thẻ thông hành thành công!\n")
except Exception as e:
    print("   -> ❌ LỖI: Không lấy được ViewState. Web có thể đã chặn.")
    exit()

# ==========================================
# TRẠM 2: GOM TOÀN BỘ LINK SẢN PHẨM
# ==========================================
print("⏳ TRẠM 2: Đang quét các danh mục để gom Link...")
danh_sach_links = []

for ten_hoa, ma_id in DANH_MUC_HOA.items():
    print(f"\n--- Đang quét: {ten_hoa.upper()} ---")

    for page in range(1, 100): # Giới hạn chạy tối đa 10 trang mỗi loại để tránh treo
        # Gói hàng (Payload) gửi lên API
        payload = {
            "__VIEWSTATE": viewstate,
            "__VIEWSTATEGENERATOR": viewstategenerator,
            "__CALLBACKID": "ctl00$cbkMaster",
            "__CALLBACKPARAM": f'c0:GET_ITEMS_{{"pageNumber":{page},"ids":[{ma_id}],"orderBy":0,"groupId":{ma_id},"rangePrice":"0","refix":""}}'
        }

        try:
            res_post = SESSION.post(URL_GOC, headers=HEADERS, data=payload)
            # Dùng Regex móc thẳng link ra khỏi chuỗi JSON lỗi
            found_links = re.findall(r'"LinkItem":"([^"]+)"', res_post.text)

            if found_links:
                for link in found_links:
                    full_link = "https://hoayeuthuong.com" + link
                    if full_link not in danh_sach_links:
                        danh_sach_links.append(full_link)
                print(f"   -> Trang {page}: Tìm thấy {len(found_links)} link mới.")
            else:
                print(f"   -> Đã hết hoa {ten_hoa} ở trang {page}. Chuyển sang loại khác.")
                break # Thoát vòng lặp trang, sang loại hoa tiếp theo

        except Exception as e:
            print(f"   -> ❌ Lỗi quét trang {page}: {e}")
        time.sleep(0.5)

tong_link = len(danh_sach_links)
print(f"\n✅ HOÀN TẤT TRẠM 2: Tổng cộng gom được {tong_link} link sản phẩm duy nhất.\n")

# ==========================================
# TRẠM 3: VÀO TỪNG LINK BÓC TÁCH DỮ LIỆU
# ==========================================
print("⏳ TRẠM 3: Bắt đầu trích xuất chi tiết và lưu file...")
du_lieu_cuoi_cung = []

# BƯỚC A: KIỂM TRA DỮ LIỆU ĐÃ CÀO TRƯỚC ĐÓ
if os.path.exists(FILE_KET_QUA):
    with open(FILE_KET_QUA, 'r', encoding='utf-8') as f:
        try:
            du_lieu_cuoi_cung = json.load(f)
            print(f"🔄 Tìm thấy dữ liệu cũ. Sẽ chạy tiếp từ sản phẩm thứ {len(du_lieu_cuoi_cung) + 1}...")
        except:
            du_lieu_cuoi_cung = []

# Lấy danh sách các URL đã cào xong để lọc bỏ
links_da_xong = {item['url'] for item in du_lieu_cuoi_cung}
links_can_cao = [l for l in danh_sach_links if l not in links_da_xong]

tong_so_moi = len(links_can_cao)
print(f"⏳ Bắt đầu trích xuất {tong_so_moi} sản phẩm còn lại...")

for idx, link in enumerate(links_can_cao, start=len(du_lieu_cuoi_cung) + 1):
    try:
        res_detail = SESSION.get(link, headers={'User-Agent': HEADERS['User-Agent']})
        soup = BeautifulSoup(res_detail.text, 'html.parser')

        # 1. Tên hoa
        ten_hoa_tag = soup.find('div', class_='r_item').find('h2')
        ten_hoa = ten_hoa_tag.text.strip() if ten_hoa_tag else "Không tên"

        # 2. Giá
        gia_cu_tag = soup.find('span', class_='old-price')
        gia_cu = gia_cu_tag.text.strip() if gia_cu_tag else ""

        gia_moi_tag = soup.find('span', class_='price')
        gia_moi = gia_moi_tag.text.strip() if gia_moi_tag else ""

        # 3. Hình ảnh
        img_tag = soup.find('div', class_='thumb-image')
        hinh_anh = "https://hoayeuthuong.com" + img_tag.find('img')['src'] if img_tag and img_tag.find('img') else ""

        # 4. Mô tả
        mo_ta_tag = soup.find('div', class_='pd_summary')
        mo_ta = mo_ta_tag.get_text(separator=" ", strip=True) if mo_ta_tag else ""
        # 5. Thành phần & Tags
        thanh_phan = [li.text.strip() for li in soup.find('ul', class_='material').find_all('li')] if soup.find('ul', class_='material') else []
        tags = [a.text.strip() for a in soup.find('div', class_='sp-items').find_all('a') if a.text.strip()] if soup.find('div', class_='sp-items') else []

        # Đóng gói dữ liệu
        item_data = {
            "id": f"SP_{idx}",
            "url": link,
            "ten_hoa": ten_hoa,
            "gia_cu": gia_cu,
            "gia_moi": gia_moi,
            "hinh_anh": hinh_anh,
            "mo_ta": mo_ta,
            "thanh_phan": thanh_phan,
            "tags": tags
        }

        du_lieu_cuoi_cung.append(item_data)
        print(f"   [{idx}/{len(danh_sach_links)}] Đã xong: {ten_hoa}")

        # Lưu file JSON
        if idx % 10 == 0 or idx == len(danh_sach_links):
            with open(FILE_KET_QUA, 'w', encoding='utf-8') as f:
                json.dump(du_lieu_cuoi_cung, f, ensure_ascii=False, indent=4)
            print(f"   💾 ---> Đã lưu Checkpoint thành công!")

    except Exception as e:
        print(f"   ❌ Lỗi ở sản phẩm {idx}: {e}")

    time.sleep(1)

print("\n🎉 XUẤT SẮC! Dữ liệu đã được lưu gọn gàng vào database_hoa.json")
